//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Subjects1 = new HashSet<Subjects>();
        }
    
        public int Id { get; set; }
        public Nullable<int> bookSubject { get; set; }
        public string bookName { get; set; }
        public string bookUrl { get; set; }
        public string bookShow { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual ICollection<Subjects> Subjects1 { get; set; }
    }
}
