//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities3 : DbContext
    {
        public DatabaseEntities3()
            : base("name=DatabaseEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audio> Audio { get; set; }
        public virtual DbSet<Avrech> Avrech { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<EnglishDetails> EnglishDetails { get; set; }
        public virtual DbSet<HebroDetails> HebroDetails { get; set; }
    }
}
