//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnglishDetails
    {
        public int Id { get; set; }
        public string Ename { get; set; }
        public string Edescription { get; set; }
    
        public virtual Avrech Avrech { get; set; }
    }
}
