//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public Subjects()
        {
            this.Audio = new HashSet<Audio>();
            this.Books = new HashSet<Books>();
            this.Movie = new HashSet<Movie>();
            this.Books1 = new HashSet<Books>();
        }
    
        public int Id { get; set; }
        public string subjectName { get; set; }
    
        public virtual ICollection<Audio> Audio { get; set; }
        public virtual ICollection<Books> Books { get; set; }
        public virtual ICollection<Movie> Movie { get; set; }
        public virtual ICollection<Books> Books1 { get; set; }
    }
}
