//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RAbout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RAbout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BVL.Resource.RAbout", typeof(RAbout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kollel Bais Vaad L’Chacamim was founded in the Ramat Shlomo neighborhood about twelve years ago by ten Talmidei Chachamim, with a vision for it to become a “Bais Vaad L’Chachamim” - a haven for great Torah Scholars, Marbitzei Torahand Mechabrei Sefarim.
        ///Over the years, an elite group of the highest-esteemed Talmidei Chachamim from throughout Yerushalayim and its surrounding have gathered in the Kollel’s Bais Medrash. Most of the Lomdim
        ///are Morei Horaah who have been, and still are, teaching Torah in the m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string about1 {
            get {
                return ResourceManager.GetString("about1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A GATHERING OF TALMIDEI CHACHAMIM.
        /// </summary>
        public static string abouttitle2 {
            get {
                return ResourceManager.GetString("abouttitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Backstory.
        /// </summary>
        public static string abouttitlt {
            get {
                return ResourceManager.GetString("abouttitlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAKING TORAH GREAT.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Kollel In Numbers.
        /// </summary>
        public static string InNumbers {
            get {
                return ResourceManager.GetString("InNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beis Vaad L&apos;Chachamim.
        /// </summary>
        public static string KollelName {
            get {
                return ResourceManager.GetString("KollelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning in the Kollel.
        /// </summary>
        public static string learning1 {
            get {
                return ResourceManager.GetString("learning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARNING AND TEACHING.
        /// </summary>
        public static string learning2 {
            get {
                return ResourceManager.GetString("learning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the Kollel Beis Vaad L’Chachamim is meant for Talmidei
        ///Chachamim who have filled their knowledge with Shas and Poskim,
        ///the learning is performed at the manner of “Libo Chafetz” - each
        ///scholar or Chavrusa learns what his heart desires. With time, though,
        ///the Bais Medrash formed Chaburos that participate in different
        ///subjects of Shas.
        ///Besides the general learning, regular Shiurim are given in the Beis
        ///Medrash by its Lomdim on certain subjects. These Shiurim include
        ///Halachos of Talmud Torah and Mela [rest of string was truncated]&quot;;.
        /// </summary>
        public static string learning3 {
            get {
                return ResourceManager.GetString("learning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shema, Tefila, Sefer Torah, Mezuza and much more. This past
        ///year, by the encouragement of HaGaon Rav Moshe Shapira, zt”l,
        ///Shiurim were given about the duty of Hishtadlus and Bitachon
        ///according to Halacha. The Shiurim are all given by the Lomdim
        ///themselves, which transformed the Kollel from individule Scholars
        ///to a Chabura that learns togetherer with unity and passion.
        ///To this day the Bais Hamedrash has published seven files of
        ///Chidushei Torah, aside from a regular file which is put together
        ///each Ere [rest of string was truncated]&quot;;.
        /// </summary>
        public static string learning4 {
            get {
                return ResourceManager.GetString("learning4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age 30 and up.
        /// </summary>
        public static string num30_77 {
            get {
                return ResourceManager.GetString("num30_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string num700 {
            get {
                return ResourceManager.GetString("num700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients of scholarships.
        /// </summary>
        public static string num87 {
            get {
                return ResourceManager.GetString("num87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual budget in dollars.
        /// </summary>
        public static string num960000 {
            get {
                return ResourceManager.GetString("num960000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performances and Recommendations.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rosh Kollel.
        /// </summary>
        public static string RoshKolel {
            get {
                return ResourceManager.GetString("RoshKolel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAKING TORAH GREAT.
        /// </summary>
        public static string RoshKolel2 {
            get {
                return ResourceManager.GetString("RoshKolel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rosh Kollel Rav Chaim Mordechei Shapira, shlita, was born and raised in Yerushalayim, and learned in Yeshivas Ateres Yisroel. He is known as one of the beloved Talmidim of the Rosh Yeshiva, HaRav Baruch Mordechei Ezrachi, shlita.
        ///After marrying the daughter of the great Dayan Rav Shlomo Dichovski, shlita, he learned in the Bais Medrash of Ramat HaSharon by HaGaon  Rav Yaakov Eidelstein, zt”l. After that he studied in Yerushalayim in Beis Medrash Taharos, where he still learns Seder Sheni. Through the y [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RoshKolel3 {
            get {
                return ResourceManager.GetString("RoshKolel3", resourceCulture);
            }
        }
    }
}
