//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RBeitVaad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RBeitVaad() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BVL.Resource.RBeitVaad", typeof(RBeitVaad).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Lessons.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books and pamphlets.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of children.
        /// </summary>
        public static string childrenNum {
            get {
                return ResourceManager.GetString("childrenNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time on its due date, the Vaad Committee releases a collection of &quot;Vayyatam&quot; about the time and is distributed both in the Holy Land and in the United States in the &quot;Tiferet Gedalyahu&quot;
        ///From time to time, the Beit Vaad Hakhamim collection is published on a variety of issues.
        /// </summary>
        public static string downloads {
            get {
                return ResourceManager.GetString("downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons and essays.
        /// </summary>
        public static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabi.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a center for a group of Torah scholars who are cleverly curled, the teachers of his generation saw the need to bring the blessing of this group of scholars to those who have yet to reach this level, such as learning and teaching.
        ///
        ///
        ///
        ///.
        /// </summary>
        public static string rasha {
            get {
                return ResourceManager.GetString("rasha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this reason, there is a group of &quot;I took you&quot; to the kollel students from Russia and the Commonwealth of Independent States, each of whom has its unique way of writing the text of the verse (Jeremiah 3:14): &quot;I took you from one city and two from a family and brought you Zion.&quot;
        ///
        ///The study of those who seek God, together with outstanding Torah scholars who have become so tired of Shas and poskim, opens up new possibilities for them to transcend learning, which would not have been possible had they been  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rasha1 {
            get {
                return ResourceManager.GetString("rasha1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group is headed by Rabbi Elisha Greenberg shlita, one of the pioneers of the Teshuvah movement in the Soviet Union in the 1980s, and after serving in Torah institutions for Russian immigrants..
        /// </summary>
        public static string rasha2 {
            get {
                return ResourceManager.GetString("rasha2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabbi Haggai Fershel, the founder and first Rosh Yeshivah at Yeshivat Ohalei Yaakov in Moscow, and the Ga&apos;on Rabbi Reuven Kuklin, who is one of the most prominent lecturers in Russian on Jewish matters, are all scholars of the Beit Midrash for the Sages.
        /// </summary>
        public static string rasha3 {
            get {
                return ResourceManager.GetString("rasha3", resourceCulture);
            }
        }
    }
}
