//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BVL.Resource.RHome", typeof(RHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beis Va&apos;ad Lachachomim.
        /// </summary>
        public static string BeisVaadLachachomim {
            get {
                return ResourceManager.GetString("BeisVaadLachachomim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booklets.
        /// </summary>
        public static string Booklets {
            get {
                return ResourceManager.GetString("Booklets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can contribute us.
        /// </summary>
        public static string contribute {
            get {
                return ResourceManager.GetString("contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can donate us on our pay pal page.
        /// </summary>
        public static string donate {
            get {
                return ResourceManager.GetString("donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullNameRequired.
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Torah.
        /// </summary>
        public static string HoldTorah {
            get {
                return ResourceManager.GetString("HoldTorah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string massag {
            get {
                return ResourceManager.GetString("massag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tora Leasons.
        /// </summary>
        public static string ToraLeasons {
            get {
                return ResourceManager.GetString("ToraLeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep in Touch.
        /// </summary>
        public static string touch {
            get {
                return ResourceManager.GetString("touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V&apos;elakachti Etchem.
        /// </summary>
        public static string VelakachtiEtchem {
            get {
                return ResourceManager.GetString("VelakachtiEtchem", resourceCulture);
            }
        }
    }
}
